name: Build and Release

on:
  push:
    branches:
      - main

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16.x'

    - name: Install dependencies
      run: npm ci

    - name: Build
      run: npm run build

    - name: Create dist.zip
      run: zip -r dist.zip dist

    - name: Create Release
      uses: ncipollo/release-action@v1
      with:
        artifacts: "dist.zip"
        token: ${{ secrets.GITHUB_TOKEN }}